# Generated by Django 5.0.9 on 2024-09-28 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscription',
            new_name='UserSubscription',
        ),
    ]
