# Generated by Django 5.0.9 on 2024-09-12 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confidiaApi', '0003_rename_username_user_id_user_remove_user_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='confidiaApi.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='projects',
            field=models.JSONField(default=list),
        ),
    ]
