# Generated by Django 5.0.9 on 2024-09-13 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confidiaApi', '0004_alter_notification_author_alter_user_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='author',
        ),
    ]
