# Generated by Django 5.0.9 on 2024-09-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confidiaApi', '0006_notification_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='id_user',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
